version: '3'
services:
  jenkins:
    ports:
    - "8080:8080"
    build: ./jenkins
  gogs:
    ports:
    - "10022:22"
    - "10080:3000"
    build: ./gogs
  artifactory:
    build: ./artifactory
  grafana:
    ports:
    - "3030:3000"
    volumes:
    - /var/lib/grafana
    links:
    - prometheus
    image: grafana/grafana
  prometheus:
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
  chef-server:
    build: ./chef-server
    entrypoint:
    - knife
    - serve
    - --chef-zero-host
    - chef-server
    - --chef-zero-port
    - '8889'
  sit:
    build: ./tomcat
    hostname: sit
    ports:
    - "8081:8080"
    privileged: true
  uat:
    build: ./tomcat
    hostname: uat
    ports:
    - "8082:8080"
    privileged: true
  prod:
    build: ./tomcat
    hostname: prod
    ports:
    - "8083:8080"
    privileged: true
