version: '3'
services:
  jenkins:
    ports:
    - "8080:8080"
    build: ./jenkins
  gogs:
    ports:
    - "10022:22"
    - "10080:3000"
    build: ./gogs
  artifactory:
    build: ./artifactory
    ports:
    - "9001:8081"
  sonarqube:
    image: sonarqube
    ports:
    - "9000:9000"
  grafana:
    ports:
    - "3030:3000"
    build: ./grafana
    links:
    - prometheus
  prometheus:
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
  chef-server:
    build: ./chef-server
    entrypoint:
    - knife
    - serve
    - --chef-zero-host
    - chef-server
    - --chef-zero-port
    - '8889'
    - --chef-repo-path
    - /root/.chef/local-mode-cache
  sit:
    build: ./tomcat
    hostname: sit
    ports:
    - "8081:8080"
    privileged: true
  sit_db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  uat:
    build: ./tomcat
    hostname: uat
    ports:
    - "8082:8080"
    privileged: true
  uat_db:
    image: postgres
    environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  prod:
    build: ./tomcat
    hostname: prod
    ports:
    - "8083:8080"
    privileged: true
  prod_db:
    image: postgres
    environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
