version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
  db-setup:
    build: hygieia/db
    depends_on:
      - db
  api:
    image: cklassen/hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"
  apiaudit:
    build: ./apiaudit
    depends_on:
      - db-setup
    ports:
      - "8084:8080"
    environment:
      MONGO_PORT: tcp://db:27017
      SPRING_DATA_MONGODB_DATABASE: dashboarddb
      SPRING_DATA_MONGODB_USERNAME: dashboarduser
      SPRING_DATA_MONGODB_PASSWORD: dbpassword
  ui:
    image: cklassen/hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"
  gitlab-feature-collector:
    image: cklassen/hygieia-gitlab-feature-collector
    depends_on:
      - db-setup
    environment:
      MONGO_PORT: tcp://db:27017
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: dashboarddb
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: dashboarduser
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: dbpassword
      GITLAB_HOST: gitlab
      GITLAB_API_TOKEN: token
  gitlab-scm-collector:
    image: cklassen/hygieia-gitlab-scm-collector
    depends_on:
      - db-setup
    environment:
      MONGO_PORT: tcp://db:27017
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: dashboarddb
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: dashboarduser
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: dbpassword
      GITLAB_HOST: gitlab
      GITLAB_API_TOKEN: token
  jenkins-build-collector:
    image: cklassen/hygieia-jenkins-build-collector
    depends_on:
      - db-setup
    environment:
      MONGO_HOST: tcp://db:27017
      MONGO_PORT: tcp://db:27017
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: dashboarddb
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: dashboarduser
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: dbpassword
      JENKINS_MASTER: http://jenkins:8080
  sonar-codequality-collector:
    image: cklassen/hygieia-sonar-codequality-collector
    depends_on:
      - db-setup
    environment:
      MONGO_HOST: tcp://db:27017
      MONGO_PORT: tcp://db:27017
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: dashboarddb
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: dashboarduser
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: dbpassword
      SONAR_URL: http://sonarqube:9000
      SONAR_VERSION: "6.72"
volumes:
  db-data:
