pipeline {
  agent any
  stages {
    stage('Start') {
      steps {
        slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}console)")
      }
    }
    stage('Build Gold Image') {
      steps {
        echo 'Building immutable infrastructure...'
        ansiColor('xterm') {
          sh 'packer build tomcat.json'
        }
      }
    }
    stage('Import Gold Image') {
      steps {
        echo 'Importing immutable infrastructure'
        sh 'cat target/tomcat.tar | docker import - custom-tomcat'
      }
    }
    stage('Provision Infrastructure') {
      steps {
        echo 'Provisioning tomcat servers...'
        sh 'docker-compose up -d'
        sh 'docker-compose restart'
      }
    }
  }
  post {
    success {
      slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
      build 'demo'
    }
    failure {
      slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
    }
  }
}
