pipeline {
  agent any
  stages {
    stage('Build & Test') {
      steps {
        echo 'Building..'
        withSonarQubeEnv('sonarqube') {
          sh './mvnw clean package sonar:sonar'
        }
      }
    }
    stage('Publish Build') {
      steps {
        withMaven(mavenSettingsConfig: '4775eac3-45b1-40cc-b683-275392fb3893') {
          echo 'Publishing to Artifactory...'
          sh './mvnw deploy -Dmaven.test.skip=true'
        }
      }
    }
    stage('SIT Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y sit -N sit -x root -P root -r tomcat::deploy,tomcat::sit'
      }
    }
    stage('SIT Tests') {
      steps {
        echo 'Running SoapUI functional tests...'
        withMaven(mavenSettingsConfig: '4775eac3-45b1-40cc-b683-275392fb3893') {
          sh './mvnw soapui-pro:test -Dendpoint=http://sit:8080 -DjunitReport=true'
        }
      }
    }
    stage('UAT Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y uat -N uat -x root -P root -r tomcat::deploy,tomcat::uat'
      }
    }
    stage('Load Tests') {
      steps {
        withMaven(mavenSettingsConfig: '4775eac3-45b1-40cc-b683-275392fb3893') {
          echo 'Running SoapUI Load Tests...'
          sh './mvnw soapui-pro:loadtest -Dendpoint=http://uat:8080 -DprintReport=true'
          input 'Deploy to Production?'
        }
      }
    }
    stage('Prod Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y prod -N prod -x root -P root -r tomcat::deploy,tomcat::prod'
      }
    }
  }
  post {
    always {
      junit 'target/surefire-reports/*.xml'
      junit 'TEST*.xml'
    }
  }
}
