pipeline {
  agent any
  stages {
    stage('Build & Test') {
      steps {
        echo 'Building..'
        withSonarQubeEnv('sonarqube') {
          sh './mvnw clean package sonar:sonar'
        }
      }
    }
    stage('Publish Build') {
      steps {
        echo 'Publishing to Artifactory...'
        sh 'curl -f -u admin:admin -T target/*.war "http://artifactory:8081/artifactory/generic-local/app.war"'
      }
    }
    stage('SIT Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y sit -N sit -x root -P root -r tomcat::deploy,tomcat::sit'
	    hygieiaDeployPublishStep(
	      applicationName: 'app',
	      artifactDirectory: 'target',
	      artifactGroup: 'com.example.stocks',
	      artifactName: '*.war',
	      artifactVersion: '',
	      buildStatus: 'Success',
	      environmentName: 'SIT'
	    )
      }
    }
    stage('SIT Tests') {
      steps {
        echo 'Running SoapUI functional tests...'
        sh './mvnw soapui-pro:test -Dendpoint=http://sit:8080 -DjunitReport=true'
      }
    }
    stage('UAT Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y uat -N uat -x root -P root -r tomcat::deploy,tomcat::uat'
	    hygieiaDeployPublishStep(
	      applicationName: 'app',
	      artifactDirectory: 'target',
	      artifactGroup: 'com.example.stocks',
	      artifactName: '*.war',
	      artifactVersion: '',
	      buildStatus: 'Success',
	      environmentName: 'UAT'
	    )
      }
    }
    stage('Load Tests') {
      steps {
        echo 'Running SoapUI Load Tests...'
        sh './mvnw soapui-pro:loadtest -Dendpoint=http://uat:8080 -DprintReport=true'
      }
    }
    stage('Prod Deploy') {
      steps {
        echo 'Deploying....'
	    sh 'knife bootstrap -y prod -N prod -x root -P root -r tomcat::deploy,tomcat::prod'
	    hygieiaDeployPublishStep(
	      applicationName: 'app',
	      artifactDirectory: 'target',
	      artifactGroup: 'com.example.stocks',
	      artifactName: '*.war',
	      artifactVersion: '',
	      buildStatus: 'Success',
	      environmentName: 'PROD'
	    )
      }
    }
  }
  post {
    always {
      junit 'target/surefire-reports/*.xml'
      junit 'TEST*.xml'
    }
  }
}