node_name                ''
client_key               '/var/jenkins_home/.chef/.pem'
validation_client_name   'chef-validator'
validation_key           '/etc/chef-server/chef-validator.pem'
chef_server_url          'http://chef-server:8889'
syntax_check_cache_path  '/var/jenkins_home/.chef/syntax_check_cache'
